services:
  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "My_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

  # Backend API
  backend:
    build:
      context: ./backend/Api
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=TestAppDb;User Id=sa;Password=My_password123;TrustServerCertificate=true;
    depends_on:
      - db
    volumes:
      - ./backend/Api/wwwroot:/app/wwwroot
    restart: always

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlserver_data:

  
  